### ISSUE TITLE
java.lang.NullPointerException in Neural Networks

### ISSUE THREAD

**Issue by kstawiski** [jpmml/openscoring#4]
I loaded neural network with these parameters:
```
{
  "id" : "WF1",
  "summary" : "Neural network",
  "properties" : {
    "created.timestamp" : "2015-07-08T03:19:37.669+0000",
    "accessed.timestamp" : null,
    "file.size" : 12690,
    "file.md5sum" : "899a823e007f417d53944666f75bf59c"
  },
  "schema" : {
    "activeFields" : [ {
      "id" : "BMI_SDS",
      "opType" : "continuous"
    }, {
      "id" : "HBA1C",
      "opType" : "continuous"
    }, {
      "id" : "INS_KG",
      "opType" : "continuous"
    }, {
      "id" : "CHOL",
      "opType" : "continuous"
    }, {
      "id" : "HDL",
      "opType" : "continuous"
    }, {
      "id" : "HA",
      "opType" : "categorical",
      "values" : [ "0", "1", "2" ]
    }, {
      "id" : "TANNER",
      "opType" : "categorical",
      "values" : [ "1", "2", "3", "4", "5" ]
    }, {
      "id" : "Male sex",
      "opType" : "categorical",
      "values" : [ "0", "1" ]
    } ],
    "groupFields" : [ ],
    "targetFields" : [ {
      "id" : "lnGDR",
      "opType" : "continuous"
    } ],
    "outputFields" : [ ]
  }
}
```

However any validation fails because of:
```
Jul 08, 2015 5:27:30 AM org.openscoring.service.ModelResource evaluate
INFO: Received EvaluationRequest{id=konrad-test, arguments={BMI_SDS=50, HBA1C=7, INS_KG=1.4, CHOL=150, HDL=40, HA=1, TANNER=1, Male sex=1}}
Jul 08, 2015 5:27:30 AM org.openscoring.service.ModelResource doEvaluate
SEVERE: Failed to evaluate
java.lang.NullPointerException
        at org.jpmml.evaluator.TypeUtil.cast(TypeUtil.java:323)
        at org.jpmml.evaluator.TypeUtil.parseOrCast(TypeUtil.java:60)
        at org.jpmml.evaluator.ArgumentUtil.prepare(ArgumentUtil.java:60)
        at org.jpmml.evaluator.ModelEvaluator.prepare(ModelEvaluator.java:113)
        at org.jpmml.evaluator.EvaluatorUtil.prepare(EvaluatorUtil.java:120)
        at org.openscoring.service.ModelResource.evaluate(ModelResource.java:538)
        at org.openscoring.service.ModelResource.doEvaluate(ModelResource.java:398)
        at org.openscoring.service.ModelResource.evaluate(ModelResource.java:259)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:308)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:403)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
```

PMML file was generated by STATISTICA and adheres to the format. As I can read from above input is correct.

**Comment by vruusmann** [comment]
The problem is related to the missing data type information. The active fields of your neural network specify the `opType` attribute, but do not specify the `dataType` attribute. However, according to the [Data Dictionary section of the PMML specification] (http://www.dmg.org/v4-2-1/DataDictionary.html) this information is mandatory.

That is, your active fields should look like this:
```
{
  "id" : "BMI_SDS",
  "dataType" : "double",
  "opType" : "continuous"
},
{
  "id" : "HA",
  "dataType" : "string",
  "opType" : "categorical",
  "values" : [ "0", "1", "2" ]
}
```

I can only conclude that STATISTICA has generated incorrect `DataField` elements. I don't have access to STATISTICA software. Can you send me this offending PMML file to my e-mail (given in my GitHub profile) so that I could analyze it in more detail and implement a workaround?

**Comment by vruusmann** [comment]
The latest versions of Openscoring let you perform strict validation of PMML documents during deployment. This functionality is disabled by default. It can be enabled by setting the value of a boolean configuration option `modelRegistry.validate` to `true`.

For example, passing it as a Java system property when starting Openscoring:
```
$ java -DmodelRegistry.validate=true -jar target/server-executable-1.2-SNAPSHOT.jar
```

**Comment by vruusmann** [comment]
So, I got myself a trial version of STATISTICA 12.7, which appears to be producing PMML models that conform to PMML schema version 3.0. Below is a sample `DataDictionary` element for the "Iris" dataset:
```
<DataDictionary numberOfFields="5">
  <DataField name="Species" optype="categorical">
    <Value value="setosa"/>
    <Value value="versicolor"/>
    <Value value="virginica"/>
  </DataField>
  <DataField name="Sepal.Length" optype="continuous"/>
  <DataField name="Sepal.Width" optype="continuous"/>
  <DataField name="Petal.Length" optype="continuous"/>
  <DataField name="Petal.Width" optype="continuous"/>
</DataDictionary>
```

Turns out that the [Data Dictionary section of the PMML specification 3.0] (http://www.dmg.org/v3-0/DataDictionary.html) does not require the `dataType` attribute. So, STATISTICA's models are valid as PMML 3.0 documents, but invalid as PMML 3.1 and newer documents.

**Comment by kstawiski** [comment]
I have added manually `dataType="...."` to `<DataField>`'s and it's working. Thank you!

**Comment by vruusmann** [comment]
I will teach the JPMML-Evaluator library to infer missing `dataType` attribute values based on `optype` attribute values: 
* `categorical` -> `string`
* `continuous` -> `double`

The Openscoring web service will be okay right after this new version of JPMML-Evaluator library becomes available. I estimate that everything will be ready by the end of next week (19 July).
